from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import os
import sys

# Import custom engines
from engine_triage import TriageEngine
from engine_routing import RoutingEngine
from map_matrix import HospitalMap

app = Flask(__name__, static_folder='static', template_folder='templates')
CORS(app)  # Enable Cross-Origin Resource Sharing

# Initialize engines
triage_engine = TriageEngine()
routing_engine = RoutingEngine()

@app.route('/')
def index():
    # Gọi chuẩn file index.html nằm trong thư mục templates
    return render_template('index.html')

@app.route('/api/map', methods=['GET'])
def get_map():
    try:
        ground_map = HospitalMap()
        # Return the full map_data so frontend can render rooms, walls, colors.
        return jsonify({"status": "success", "map_data": ground_map.map_data})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/init', methods=['GET'])
def get_initial_triage():
    """Returns the root of the symptom tree to kickstart the UI."""
    try:
        if not triage_engine.symptoms_data:
            raise ValueError("Symptoms data is missing or corrupt.")
        
        # Return only the question and options to prevent sending the whole tree if desired.
        # But to allow zero-latency UX, returning the whole tree might be better.
        # Following the recent architecture shift, we just return the root node.
        root_node = triage_engine.process_triage({})
        return jsonify(root_node)
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/triage', methods=['POST'])
def api_triage():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"status": "error", "message": "Missing payload"}), 400
            
        result = triage_engine.process_triage(data)
        if "error" in result:
            return jsonify({"status": "error", "message": result["error"]}), 422
            
        return jsonify(result)

    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route('/api/route', methods=['POST'])
def api_route():
    try:
        data = request.get_json()
        if not data or 'start' not in data or 'goal' not in data:
            return jsonify({"status": "error", "message": "Missing start or goal in payload"}), 400
            
        start = data['start']
        goal = data['goal']
        
        # Validation
        if len(start) != 3 or len(goal) != 3:
            return jsonify({"status": "error", "message": "Start and goal must be arrays of length 3 [r, c, z]"}), 400

        hospital_map = HospitalMap()
        # Create grid dictionary for all floors between start and goal
        # Use the grid generated by the frontend which handles CELL_SPANS correctly
        grid = data.get('grid', {})
        if not grid:
            min_z = min(start[2], goal[2])
            max_z = max(start[2], goal[2])
            for z in range(min_z, max_z + 1):
                grid[str(z)] = hospital_map.get_grid_for_floor(z).tolist()
            
        # Also pass hospital_map reference to routing engine to check elevators
        result = routing_engine.find_path(start, goal, grid, hospital_map)
        
        if result["status"] == "blocked":
            return jsonify(result), 422
            
        return jsonify(result)

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

if __name__ == '__main__':
    # Force run in debug mode for development
    app.run(host='0.0.0.0', port=5000, debug=True)
